#spring:
#thymeleaf:
#cache: false
##    配置文件位置
#messages:
#basename: i18n.login
#datasource:
#driver-class-name: com.mysql.cj.jdbc.Driver
#url: jdbc:mysql://localhost:3306/BookMall?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#username: root
#password: 19950304
#type: com.alibaba.druid.pool.DruidDataSource
#
#mybatis:
#type-aliases-package: com.example.springbootdemo1.pojo
#mapper-locations: classpath:Mybatis/mapper/*.xml
devtools:
  restart:
    # 开启热部署功能
    enabled: true
    # 设置热部署要监听的目录
    additional-paths: src/main/java
    # 解决项目自动重新编译后接口报404的问题
    poll-interval: 3000
    quiet-period: 1000
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    cache: false
    mode: HTML5
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .html
  messages:
    basename: i18n.login
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BookMall?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 19950304
server:
  port: 8089
mybatis:
  type-aliases-package: com.example.m2.pojo
  mapper-locations:
    -  classpath:/mapper/*.xml

